# @package _group_

hydra:
  run:
    dir: .

defaults:
    - _self_
    - task: null
    - model: null
    - criterion: null #cross_entropy
    - optimizer: null
    - lr_scheduler: null #fixed
    - bpe: null
    - tokenizer: null
    - scoring: null
    - generation: null
    - common_eval: null
    - eval_lm: null